"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { api, inr, Opportunity } from "@/lib/api";

const STATUS_OPTIONS = [
  "ALL",
  "OPEN",
  "DECIDED",
  "EXECUTING",
  "RECOVERED",
  "LOST",
  "EXPIRED",
];

export default function OpportunitiesPage() {
  const [rows, setRows] = useState<Opportunity[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [statusFilter, setStatusFilter] = useState("ALL");

  const load = useCallback(() => {
    setError(null);

    api<Opportunity[]>("/recovery/opportunities?limit=100")
      .then(setRows)
      .catch((e) => setError(String(e)));
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const filteredRows = useMemo(() => {
    if (statusFilter === "ALL") {
      return rows;
    }

    return rows.filter((o) => o.status === statusFilter);
  }, [rows, statusFilter]);

  const counts = useMemo(() => {
    return {
      total: rows.length,
      active: rows.filter((o) =>
        ["OPEN", "DECIDED", "EXECUTING"].includes(o.status)
      ).length,
      recovered: rows.filter((o) => o.status === "RECOVERED").length,
      expired: rows.filter((o) => o.status === "EXPIRED").length,
    };
  }, [rows]);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <h1 className="text-2xl font-semibold">Recovery Opportunities</h1>
          <p className="mt-1 text-sm text-slate-500">
            Autonomous recovery decisions generated by REVIVE
          </p>
        </div>

        <button
          onClick={load}
          className="rounded-md border border-slate-700 px-3 py-1.5 text-sm text-slate-300 transition hover:bg-slate-800"
        >
          Refresh
        </button>
      </div>

      {error && (
        <div className="rounded-lg border border-rose-500/20 bg-rose-500/10 px-4 py-3 text-sm text-rose-400">
          Backend unavailable: {error}
        </div>
      )}

      {/* Summary */}
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <SummaryCard
          label="Total Opportunities"
          value={counts.total}
        />

        <SummaryCard
          label="Active"
          value={counts.active}
          accent="text-sky-400"
        />

        <SummaryCard
          label="Recovered"
          value={counts.recovered}
          accent="text-emerald-400"
        />

        <SummaryCard
          label="Expired"
          value={counts.expired}
          accent="text-slate-400"
        />
      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-2">
        {STATUS_OPTIONS.map((status) => {
          const active = statusFilter === status;

          return (
            <button
              key={status}
              onClick={() => setStatusFilter(status)}
              className={`rounded-md border px-3 py-1.5 text-xs font-medium transition ${
                active
                  ? "border-emerald-500/40 bg-emerald-500/10 text-emerald-300"
                  : "border-slate-800 bg-slate-900/40 text-slate-500 hover:bg-slate-800 hover:text-slate-300"
              }`}
            >
              {status.replace("_", " ")}
            </button>
          );
        })}
      </div>

      {/* Table */}
      <div className="overflow-x-auto rounded-xl border border-slate-800 bg-slate-900/60">
        <table className="w-full min-w-[1050px] text-sm">
          <thead className="text-left text-xs uppercase tracking-wide text-slate-500">
            <tr className="border-b border-slate-800">
              <th className="px-4 py-3">Opp #</th>
              <th>Payment</th>
              <th>Risk</th>
              <th>Root Cause</th>
              <th>Prob.</th>
              <th>Best Action</th>
              <th className="text-right">Expected Recovery</th>
              <th>Timing</th>
              <th className="text-right">Confidence</th>
              <th>Status</th>
            </tr>
          </thead>

          <tbody>
            {filteredRows.map((o) => (
              <tr
                key={o.id}
                className="border-b border-slate-800/50 transition hover:bg-slate-800/30"
              >
                {/* Opportunity */}
                <td className="px-4 py-3">
                  <Link
                    href={`/decisions/${o.id}`}
                    className="font-medium text-emerald-400 hover:underline"
                  >
                    #{o.id}
                  </Link>
                </td>

                {/* Payment */}
                <td className="text-slate-400">
                  #{o.payment_id}
                </td>

                {/* Risk */}
                <td>
                  <RiskBadge level={o.risk_level} />
                </td>

                {/* Root Cause */}
                <td className="text-slate-400">
                  {o.root_cause}
                </td>

                {/* Probability */}
                <td>
                  {o.recovery_probability != null
                    ? `${(o.recovery_probability * 100).toFixed(0)}%`
                    : "—"}
                </td>

                {/* Action */}
                <td className="font-medium">
                  {o.recommended_action ?? "—"}
                </td>

                {/* Expected Recovery */}
                <td className="text-right text-emerald-300">
                  {o.expected_recovery != null
                    ? inr(o.expected_recovery)
                    : "—"}
                </td>

                {/* Timing */}
                <td className="text-slate-400">
                  {o.recommended_timing ?? "—"}
                </td>

                {/* Confidence */}
                <td className="text-right">
                  {o.confidence != null
                    ? `${(o.confidence * 100).toFixed(0)}%`
                    : "—"}
                </td>

                {/* Status */}
                <td>
                  <StatusBadge status={o.status} />
                </td>
              </tr>
            ))}

            {!filteredRows.length && (
              <tr>
                <td
                  colSpan={10}
                  className="px-4 py-12 text-center"
                >
                  <p className="text-sm text-slate-500">
                    {statusFilter === "ALL"
                      ? "No recovery opportunities yet."
                      : `No ${statusFilter.toLowerCase()} opportunities.`}
                  </p>

                  {statusFilter === "ALL" && (
                    <p className="mt-1 text-xs text-slate-600">
                      Run the demo script or POST to /recovery/decide.
                    </p>
                  )}
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* Footer */}
      <div className="flex items-center justify-between text-xs text-slate-600">
        <span>
          Showing {filteredRows.length} of {rows.length} opportunities
        </span>

        <span>
          Click an opportunity to inspect the decision graph
        </span>
      </div>
    </div>
  );
}

function SummaryCard({
  label,
  value,
  accent = "text-slate-200",
}: {
  label: string;
  value: number;
  accent?: string;
}) {
  return (
    <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-4">
      <p className="text-xs uppercase tracking-wide text-slate-500">
        {label}
      </p>

      <p className={`mt-2 text-2xl font-bold ${accent}`}>
        {value}
      </p>
    </div>
  );
}

function RiskBadge({ level }: { level: string }) {
  const map: Record<string, string> = {
    CRITICAL: "bg-rose-500/15 text-rose-400",
    HIGH: "bg-orange-500/15 text-orange-300",
    MEDIUM: "bg-amber-500/15 text-amber-300",
    LOW: "bg-emerald-500/15 text-emerald-300",
  };

  return (
    <span
      className={`rounded px-2 py-0.5 text-xs font-medium ${
        map[level] ?? "bg-slate-700 text-slate-300"
      }`}
    >
      {level}
    </span>
  );
}

function StatusBadge({ status }: { status: string }) {
  const map: Record<string, string> = {
    OPEN: "bg-amber-500/15 text-amber-300",
    DECIDED: "bg-violet-500/15 text-violet-300",
    EXECUTING: "bg-sky-500/15 text-sky-300",
    RECOVERED: "bg-emerald-500/15 text-emerald-300",
    LOST: "bg-rose-500/15 text-rose-400",
    EXPIRED: "bg-slate-600/30 text-slate-400",
  };

  return (
    <span
      className={`rounded px-2 py-0.5 text-xs font-medium ${
        map[status] ?? "bg-slate-700 text-slate-300"
      }`}
    >
      {status}
    </span>
  );
}

export const dynamic = "force-dynamic";